[package]
name = "mf"
version = "0.1.0"
authors = ["wafelack <wafelack@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
libc = "0.2.95"
