.TH MF 1 2021-06-25 Miniutils "User Commands"

.SH NAME
mf \- find files

.SH SYNOSPIS
.B mf
[\fIFOLDER\fR]
[\fIOPTION\fR]...

.SH DESCRIPTION
Find files in a directory hierarchy.

If no FOLDER is specified, . (the current directory) is used.

By default, goes into every directory beyond the FOLDER, however, this could be changed with the \fB--maxdepth\fR option.

.SH OPTIONS
\fB-d\fR, \fB--depth\fR            Process the directory content before the directory itself.

\fB-x\fR, \fB--exec\fR \fICOMMAND\fR
                       The command to run for each file. `{}` is replaced by the 
                       file's name in the command.

\fB-g\fR, \fB--gid\fR \fIID\fR           File owner belongs to the group that has id ID.

\fB-n\fR, \fB--name\fR \fIPAT\fR...      File name matches pattern(s) PAT.

\fB-p\fR, \fB--path\fR \fIPAT\fR...      File path matches pattern(s) PAT.

\fB-P\fR, \fB--perms\fR \fIBITS\fR       File has permission bits set to BITS.

\fB-t\fR, \fB--type\fR  \fITYPE\fR       
                       File is of type TYPE. Type `f` stands for file 
                       and `d` stands for directory.

\fB-u\fR, \fB--uid\fR \fIID\fR           File owner has user id ID.

\fB-m\fR, \fB--maxdepth\fR \fIDEPTH\fR   Reach at most DEPTH level of nested directories.

\fB-h\fR, \fB--help\fR             Display help and exit.

\fB-V\fR, \fB--version\fR          Display version information and exit.

.SH PATTERNS

Patterns work with wildcards, a wildcard matches every set of characters.
For example `*.rs` will match all the files which name ends in `.rs`, and `*foo*` will match all the files containing `foo` in their names.

.SH SEE ALSO
\fBls\fR(1), \fBinode\fR(7)

.SH AUTHOR
Written by Wafelack.

.SH REPORTING BUGS
Please report any bug to the mf repository issues page:
.br
    <https://github.com/miniutils/mf/issues/new>.

.SH COPYRIGHT
Copyright (C) 2021 Miniutils.
.br
License GPLv3: GNU General Public License version 3.0.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
